---
    name: "Tagged Release"

    on:
      push:
        tags:
          - "*"

    jobs:
      tagged-release:
        name: "Tagged Release"
        runs-on: "ubuntu-latest"

        steps:
          - uses: actions/checkout@v3

          - name: Set up QEMU
            uses: docker/setup-qemu-action@v3

          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v3

          - name: Login to GitHub Packages Docker Registry
            uses: docker/login-action@v3
            with:
              registry: ghcr.io
              username: ${{ github.repository_owner }}
              password: ${{ secrets.GITHUB_TOKEN }}

          - name: Build and push
            id: docker_build
            uses: docker/build-push-action@v5
            with:
              context: .
              push: true
              tags: ghcr.io/bricemichalski/${{ github.event.repository.name }}/${{ github.event.repository.name }}:${{ github.ref_name }}
              platforms: linux/amd64,linux/arm64
              build-args: |
                module=${{ github.event.repository.name }}
                version=${{ github.ref_name }}
                gh_token=${{ secrets.GITHUB_TOKEN }}
              secrets: |
                "github_token=${{ secrets.GITHUB_TOKEN }}"

          - uses: marvinpinto/action-automatic-releases@latest
            with:
              repo_token: "${{ secrets.GITHUB_TOKEN }}"
              prerelease: false
              title: "${{ github.ref_name }}"
              files: |
                target/*.jar
